apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  labels:
    app: my-flask-app
spec:
  type: ClusterIP
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 5000         # Exposed port of the service
      targetPort: 5000   # Port where your Flask application is running

