apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 5000            # This is the port your app listens to inside the container
      targetPort: 5000       # The container port your Flask app is running on
      nodePort: 30007        # Optional: You can specify a NodePort or let Kubernetes assign one (default range: 30000-32767)
